name: myapp
description: A exported flutter project from FUNCTION12

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  get_storage: ^2.1.1
  cupertino_icons: ^1.0.2
  platform_device_id: ^1.0.1
  shared_preferences: ^2.0.18
  currency_text_input_formatter: ^2.1.7
  flutter_spinkit: ^5.1.0
  cached_network_image: ^3.2.3
  statsfl: ^2.3.0
  sized_context: ^1.0.0+1
  provider: ^6.0.5
  darq: ^1.2.1
  connectivity_plus: ^3.0.3
  universal_platform: ^1.0.0+1
  fluttertoast: ^8.2.2
  json_annotation: ^4.8.0
  freezed_annotation: ^2.2.0
  flutter_bloc: ^8.1.2
  system_info: ^1.0.1
  iphone_has_notch: ^1.0.0
  logger: ^2.0.1
  awesome_notifications: ^0.6.19
  dio: ^5.2.1+1
  google_fonts: ^4.0.4
  salomon_bottom_bar: ^3.3.2
  bloc: ^8.1.2
  permission_handler: ^10.4.3
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  otp_text_field: ^1.1.3
  timer_count_down: ^2.2.2
  rxdart: ^0.27.7
  event_bus: ^2.0.0
  overlay_support: ^2.1.0
  get_it: ^7.6.0
  flutter_form_builder: ^9.2.1
  dio_cache_interceptor: ^3.5.0
  introduction_screen: ^3.1.14
  get: ^4.6.6
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.10+1
  sqflite: ^2.3.3
  path: ^1.9.0
  path_provider: ^2.1.3
  sentry_flutter: ^7.14.0
  # retrofit_generator: ^7.0.8

dev_dependencies:
  flutter_flavorizr: ^2.1.6
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.2.19
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_gen_runner:
  freezed:
  retrofit_generator: ">=4.0.0 <8.0.0"
  json_serializable:
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - .env.dev
    - .env.stg
    - .env.prod

    - assets/images/
    - assets/icons/
    - assets/svg/

flavorizr:
  ide: "vscode"
  flavors:
    dev:
      app:
        name: "Wallet (dev)"
      android:
        applicationId: "com.cryptowallet.dev.app"
      ios:
        bundleId: "com.cryptowallet.dev.app"

    stg:
      app:
        name: "Wallet (stg)"
      android:
        applicationId: "com.cryptowallet.stg.app"
      ios:
        bundleId: "com.cryptowallet.st.app"

    prod:
      app:
        name: "Wallet"
      android:
        applicationId: "com.core.app"
      ios:
        bundleId: "com.core.app"

flutter_native_splash:
  color: "#F77737"
  image: assets/app_icon/splash_icon.png
  android_12:
    color: "#F77737"
    web: false

